In [12]:
import pandas as pd
from functions import read_md

In [2]:
history = pd.read_csv("gym.csv")

In [6]:
history.columns

Index(['date', 'name', 'variant', 'value', 'unit', 'category', 'subcategory',
       'note', 'last', 'max', 'pin', 'goal'],
      dtype='object')

In [18]:
history.groupby(["category", "subcategory"]).count()["date"] /31.5

category   subcategory
arms       bizeps         2.031746
           triceps        1.936508
back       inner          1.301587
           lower          1.079365
           outer          2.666667
           upper          1.269841
cardio     cardio         0.031746
           legs           1.206349
chest      central        1.174603
           inner          1.142857
           lower          1.968254
           upper          1.174603
legs       abdominals     0.857143
           calves         0.920635
           full           1.650794
           hamstrings     0.507937
           quadriceps     0.920635
shoulders  front          0.031746
           side           1.174603
           upper          0.920635
Name: date, dtype: float64

In [21]:
goals = read_md('../../obsidian/living/fitness/Gym goals.md')
goals

     category subcategory goal
0        back       upper    1
1        back       outer    2
2        back       lower    1
3        back       inner    2
4        arms      bizeps    3
5        arms     triceps    2
6      cardio        legs    3
7       chest     central    1
8       chest       upper    1
9       chest       lower    2
10  shoulders       upper    1
11  shoulders        side    2
12      chest       inner    1
13       legs        full    2
14       legs  quadriceps    1
15       legs      calves    1
16       legs  abdominals    1

In [28]:
history.drop("goal", axis=1,inplace=True)

In [30]:
history = history.join(goals.set_index(["category", "subcategory"]), on=["category", "subcategory"])

In [32]:
history.goal = history.goal.fillna(0)

In [16]:
history["date"].nunique() /4

31.5

In [20]:
history.groupby(["category", "subcategory"]).mean(numeric_only=True)

                            value        last         max  goal
category  subcategory
arms      bizeps        13.738281   13.722656   14.695312   NaN
          triceps       27.693443   27.143103   28.640678   NaN
back      inner         45.212195   45.671795   49.397436   NaN
          lower         62.352941   63.787879   66.515152   NaN
          outer         41.178571   40.780488   44.731707   NaN
          upper         49.100000   49.315789   52.447368   NaN
cardio    cardio        16.000000   20.000000   30.000000   NaN
          legs          44.252632   43.884211   50.773684   NaN
chest     central       57.635135   58.611111   63.055556   NaN
          inner         76.430556   77.042857   83.257143   NaN
          lower         20.937097   20.918333   22.454098   NaN
          upper         40.878378   41.271429   44.111111   NaN
legs      abdominals    60.666667   60.222222   63.444444   NaN
          calves        66.637931   65.446429   73.035714   NaN
          full         136.326923  136.980000  160.440000   NaN
          hamstrings    48.187500   47.733333   55.000000   NaN
          quadriceps    86.724138   87.500000   93.250000   NaN
shoulders front         10.000000         NaN         NaN   NaN
          side           5.724324    5.550000    6.145833   NaN
          upper         29.206897   29.178571   33.821429   NaN

In [35]:
history.set_index("date").to_csv("gym.csv")